spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081   # The address of your user-service 8081
          predicates:
            - Path=/api/auth/**       # Route all /api/users/** requests to user-service
        - id: restaurant-service
          uri: http://localhost:8082   # The address of your restaurant-service 8082
          predicates:
            - Path=/api/restaurants/** # Route all /api/restaurants/** requests to restaurant-service
        - id: dish-service
          uri: http://localhost:8083   # The address of your menu-service 8083
          predicates:
            - Path=/api/menus/**       # Route all /api/menus/** requests to dishes-service
        - id: order-service
          uri: http://localhost:8084   # The address of your order-service 8084
          predicates:
            - Path=/api/orders/**      # Route all /api/orders/** requests to order-service

  mvc:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


server:
  port: 8080


